name: Tests
on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: Install dependencies
        run: pnpm install
      - name: tests
        run: pnpm run test:ci
        